### ISSUE TITLE
Word: Add possibility to add locations

### ISSUE THREAD

**Issue by matumaros** [pyfection/boarbar#28]
People with high enough reputation should be able to add locations where they have heard that word being used.

**Comment by Godod** [comment]
It's should be country, city or geo location?

**Comment by matumaros** [comment]
I'm not quite sure how it's going to be in the end. I just wrote this issue so I don't lose track of it.
We would have to discuss this in more detail before realizing it.

**Comment by matumaros** [comment]
How about using [GeoDjango](https://docs.djangoproject.com/en/1.10/ref/contrib/gis/)? I have never used it, which is why I can't judge if it would be overkill for this project.
The only things I would like to do is to:
- convert addresses to longitude and latitude
- store longitude and latitude in the database
- display those coordinates as dots on a map

**Comment by matumaros** [comment]
Maybe this would be a good alternative?: https://pypi.python.org/pypi/django-easy-maps

**Comment by Godod** [comment]
@matumaros Never work with geolocation, but you can try ;) worse wont be) If you only need store longitude and latitude, we can using [postgis](https://docs.djangoproject.com/en/1.10/ref/contrib/gis/install/postgis/). And yes - try django-easy-maps.
Again, I don't have enough experience with postgis or geolocation.

P.S. Try it, because without trying you don't know, it's good or bad

**Comment by matumaros** [comment]
@Godod Yeah, I think django-easy-maps will be the best solution. I guess we don't even need to store the geo location then, only the address.

**Comment by Godod** [comment]
@matumaros What address? I think, best solution is store long and lat to database. Storing geo location will greater accuracy when address will be show on map

**Comment by pyfection** [comment]
Solved and displayed on Google Maps as heatmap
